# Generated by Django 3.2.12 on 2022-03-22 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertie',
            name='latitude',
            field=models.DecimalField(decimal_places=16, max_digits=16),
        ),
        migrations.AlterField(
            model_name='propertie',
            name='longitude',
            field=models.DecimalField(decimal_places=16, max_digits=16),
        ),
        migrations.AlterField(
            model_name='propertie',
            name='size',
            field=models.DecimalField(decimal_places=1, max_digits=100),
        ),
    ]
