# Generated by Django 3.2.12 on 2022-03-23 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0003_auto_20220321_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='sex',
            field=models.CharField(max_length=11),
        ),
    ]
